spring:
  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp


logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG

s3:
  accessKey: <access key id>
  secretKey: <secret access key>
  bucketName: <name of the bucket>

albums:
  url: http://album-service-sanjunaircognizant.cfapps.io/albums
movies:
  url: http://movie-service-sanjunaircognizant.cfapps.io/movies
